theme: jekyll-theme-leap-day
title: VMagicMirror
description: Move your VRM. Use your Keyboard and Mouse.

#show_downloads: "false"

github:
  zip_url: https://baku-dreameater.booth.pm/items/1272298
  manual_index_url: https://malaybaku.github.io/VMagicMirrorManual/index.html

booth:
  download_url: https://baku-dreameater.booth.pm/items/1272298
